### ISSUE TITLE
Keep getting "Redirected to login page" even after re-installing

### ISSUE THREAD

**Issue by Yangelato** [AzeemIdrisi/InstaLoaderApp#16]
**Describe the bug**

It worked fine this morning then I got HTTP 401 error on the app so I re-installed the app and from then after I put the username and press download all media, a few seconds after download started message, and error occurs (screenshot below) and it is still the same after reinstall

**Expected behavior**
Download the profile.

**Screenshots**

![Screenshot_20231128_143703_InstaLoaderApp](https://github.com/AzeemIdrisi/InstaLoaderApp/assets/152250620/93673d75-9a4d-4229-8438-7e52c276c941)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android One UI 6.1
 - Version: 1.4

**Additional context**
I kept on getting "http 401 error" before re-installing the app.

**Comment by AzeemIdrisi** [comment]
This is an error message from the underlying [instaloader](https://github.com/instaloader/instaloader) library, And this happens when Instagram detects too many requests from an IP address. The only solution for this is to change your IP address. You can connect to some other Wi-Fi network or Mobile Data and it will work fine.

**Comment by Yangelato** [comment]
Resolved. Thank you.
